# Generated by Django 5.1.1 on 2025-07-06 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0002_alter_tweet_options_tweet_likes_userprofile"),
    ]

    operations = []
