# Generated by Django 5.1.1 on 2025-07-06 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweet", "0004_tweet_parent_tweet_tweet_privacy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(
                blank=True, help_text="Company you work for", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True, help_text="Cover photo", null=True, upload_to="covers/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_username",
            field=models.CharField(
                blank=True, help_text="GitHub username", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="Verified account"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(
                blank=True, help_text="Your current job title", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_profile",
            field=models.URLField(blank=True, help_text="LinkedIn profile URL"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_birth_date",
            field=models.BooleanField(
                default=False, help_text="Show birth date publicly"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_email",
            field=models.BooleanField(default=False, help_text="Show email publicly"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="theme_color",
            field=models.CharField(
                default="#1DA1F2", help_text="Profile theme color", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="twitter_handle",
            field=models.CharField(
                blank=True, help_text="Twitter username (without @)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, help_text="Profile picture", null=True, upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Tell people a little about yourself",
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, help_text="Your birth date", null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="is_private",
            field=models.BooleanField(default=False, help_text="Make profile private"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True, help_text="Where you're from", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, help_text="Your website or portfolio"),
        ),
    ]
